#!/usr/bin/env bash
# Redirection

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#sudo sed -i '/listen 80;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent; /etc/nginx/sites-available/default
sudo sed -i 's#server_name _;#&\n\tlocation /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }#' /etc/nginx/sites-available/default

sudo service nginx restart
