#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string
# Ceci n'est pas une page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i 's#server_name _;#&\n\tlocation /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }\n\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}#' /etc/nginx/sites-available/default
sudo service nginx start
