#!/usr/bin/env bash
# installs and configures HAproxy on lb-01
sudo apt-get -y update
sudo apt-get install -y haproxy

tempfile=$(mktemp)

echo -e '\n frontend http_front\n\tbind *:80\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver web-01 35.153.18.12:80 check\n\tserver web-02 52.3.243.162:80 check' >> "$tempfile"

sudo cp "$tempfile" /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
sudo systemctl enable haproxy
sudo rm "$tempfile"
