#!/usr/bin/env bash
#cofigures nginx to run as nginx user
pkill apache2
chown nginx:nginx /etc/nginx -R
chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
